# Generated by Django 4.2.20 on 2025-03-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='trilhas/')),
                ('area', models.CharField(choices=[('dados', 'Ciência de Dados'), ('dev', 'Desenvolvimento de Software'), ('automacao', 'Automação'), ('ia', 'Inteligência Artificial')], max_length=15)),
                ('total_cursos', models.PositiveIntegerField(default=0)),
                ('total_horas', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cursos', models.ManyToManyField(blank=True, related_name='trilhas', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Trilha',
                'verbose_name_plural': 'Trilhas',
                'ordering': ['nome'],
            },
        ),
    ]
