# Generated by Django 5.0.6 on 2025-03-27 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_trilha'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='aula',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ArquivoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='aulas/arquivos/')),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='cursos.aula')),
            ],
        ),
    ]
