# Generated by Django 5.0.6 on 2025-03-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_aula_video_url_alter_aula_conteudo_arquivoaula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='aulas/videos/'),
        ),
    ]
