# Generated by Django 5.0.6 on 2025-04-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_remove_curso_desconto_remove_curso_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tipo_conteudo',
            field=models.CharField(choices=[('texto', 'Somente Texto'), ('video', 'Somente Vídeo'), ('texto_video', 'Texto e Vídeo'), ('anexos', 'Somente Anexos'), ('completo', 'Texto, Vídeo e Anexos'), ('texto_anexos', 'Texto e Anexos'), ('video_anexos', 'Vídeo e Anexos'), ('nenhum', 'Não especificado')], default='nenhum', max_length=20),
        ),
    ]
