# Generated by Django 5.0.6 on 2025-05-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_curso_tipo_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Curso Gratuito'),
        ),
    ]
