# Generated by Django 5.0.6 on 2025-05-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_curso_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='video_url',
        ),
        migrations.AddField(
            model_name='aula',
            name='video_embed_code',
            field=models.TextField(blank=True, null=True, verbose_name='Código de Incorporação do Vídeo (iframe)'),
        ),
    ]
