# Generated by Django 5.0.6 on 2025-05-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_remove_aula_video_url_aula_video_embed_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='trilha',
            options={'ordering': ['titulo'], 'verbose_name': 'Trilha de Aprendizagem', 'verbose_name_plural': 'Trilhas de Aprendizagem'},
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='atualizado_em',
            new_name='data_atualizacao',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='criado_em',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='trilha',
            old_name='atualizado_em',
            new_name='data_atualizacao',
        ),
        migrations.RenameField(
            model_name='trilha',
            old_name='criado_em',
            new_name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='tipo_conteudo',
        ),
        migrations.RemoveField(
            model_name='trilha',
            name='area',
        ),
        migrations.RemoveField(
            model_name='trilha',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='trilha',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='trilha',
            name='total_cursos',
        ),
        migrations.RemoveField(
            model_name='trilha',
            name='total_horas',
        ),
        migrations.AddField(
            model_name='curso',
            name='categoria',
            field=models.CharField(default='Indefinido', max_length=100),
        ),
        migrations.AddField(
            model_name='curso',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trilha',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='trilhas_capas/', verbose_name='Imagem de Capa'),
        ),
        migrations.AddField(
            model_name='trilha',
            name='publicada',
            field=models.BooleanField(default=False, verbose_name='Publicada'),
        ),
        migrations.AddField(
            model_name='trilha',
            name='titulo',
            field=models.CharField(default='Nova Trilha', max_length=200, verbose_name='Titulo da Trilha'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem de capa para o curso.', null=True, upload_to='cursos/'),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='trilhas', to='cursos.curso', verbose_name='Cursos na Trilha'),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='slug',
            field=models.SlugField(help_text='Será preenchido automaticamente a partir do título.', max_length=200, unique=True),
        ),
    ]
