# Generated by Django 5.0.6 on 2025-05-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_alter_curso_options_alter_trilha_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='area',
            field=models.CharField(blank=True, choices=[('dados', 'Ciência de Dados'), ('dev', 'Desenvolvimento de Software'), ('automacao', 'Automação'), ('ia', 'Inteligência Artificial')], max_length=15, null=True, verbose_name='Área de Conhecimento'),
        ),
    ]
