# Generated by Django 5.0.6 on 2025-06-05 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_trilha_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trilha',
            name='cursos',
        ),
        migrations.AddField(
            model_name='trilha',
            name='cursos_old',
            field=models.ManyToManyField(blank=True, related_name='trilhas_old', to='cursos.curso'),
        ),
        migrations.CreateModel(
            name='TrilhaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('section_name', models.CharField(blank=True, help_text='Ex: Módulo 1, Fundamentos, Avançado', max_length=100, null=True, verbose_name='Nome da Seção (Opcional)')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.trilha')),
            ],
            options={
                'verbose_name': 'Curso na Trilha',
                'verbose_name_plural': 'Cursos da Trilha',
                'ordering': ['order'],
                'unique_together': {('trilha', 'curso')},
            },
        ),
    ]
