# Generated by Django 5.0.6 on 2025-06-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_remove_trilha_cursos_trilha_cursos_old_trilhacurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='trilhas_associadas', through='cursos.TrilhaCurso', to='cursos.curso', verbose_name='Cursos na Trilha'),
        ),
    ]
