# Generated by Django 5.0.6 on 2025-06-05 15:33

from django.db import migrations

def transfer_trilha_cursos(apps, schema_editor):
    Trilha = apps.get_model('cursos', 'Trilha')
    TrilhaCurso = apps.get_model('cursos', 'TrilhaCurso')
    Curso = apps.get_model('cursos', 'Curso')
    
    for trilha_instance in Trilha.objects.all():
        order_counter = 0
        if hasattr(trilha_instance, 'cursos_old'):
            for curso_instance in trilha_instance.cursos_old.all():
                TrilhaCurso.objects.create(
                    trilha=trilha_instance,
                    curso=curso_instance,
                    order=order_counter
                )
                order_counter += 1

class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_trilha_cursos'),
    ]

    operations = [
        migrations.RunPython(transfer_trilha_cursos),
    ]
