# Generated by Django 5.0.6 on 2025-06-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_auto_20250605_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trilha',
            name='cursos_old',
        ),
    ]
