# Generated by Django 5.0.6 on 2025-06-18 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_alter_trilhacurso_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AulaConcluida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateTimeField(auto_now_add=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusoes', to='cursos.aula')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas_concluidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aula Concluída',
                'verbose_name_plural': 'Aulas Concluídas',
                'unique_together': {('user', 'aula')},
            },
        ),
    ]
